EndpointResolverv2 WIP
jonemo/botocore pull request #1
Opened 2022-09-20 20:52 UTC by jonemo

2022-09-23 17:29 UTC, nateprewitt reviewed
Great start, thanks for putting this together. I left some high level feedback, happy to answer any questions or further discuss tradeoffs for the changes.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/args.py
> +        if endpoints_ruleset_data is None:
This whole block may be better off in its own builder function. That way we can isolate the e20 logic into its own compartment.

`endpoint_resolver_v2 = self._build_endpoint_resolver(...)`

2022-09-23 17:29 UTC, nateprewitt commented on botocore/args.py
> +            endpoint_resolver_v2 = None
I don't have a great name idea yet, but we should brainstorm alternatives to `endpoint_resolver_v2`. I'd prefer we avoid versioning info leaking into the class/function/var names if possible.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/args.py
> +                eprv2_region_name = region_name
Could we make the comment here a bit clearer on why s3/sts are special cased?

2022-09-23 17:29 UTC, nateprewitt commented on botocore/args.py
> +        elif client_endpoint_url is not None and not is_s3_accelerate_url(
nit; we might make `is_s3_accelerate_url` more tolerant of `None`.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/handlers.py
>              signature_version = f's3{signature_version}'
I'd be curious what cases we're hitting that require this. If this isn't `s3` I'd be hesitant to make these signers synonymous with disableDoubleEncoding. If we someday get another service with this attribute, it shouldn't automatically be assumed to be `s3`.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/handlers.py
> +def fix_s3_path(model, params, **kwargs):
Was the decision reached on this issue that SDKs need to figure out how to assemble paths after endpoint resolution? This seems a little unfortunate we have to handle this outside of the e20 process, but maybe it can't be avoided.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/handlers.py
> +                pass
This is almost its own `is_valid_arn` function, don't know if that's needed but I think David had to do something similar in his provider.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +            )
I'm kind of hesitant to use `_replace` here especially since we don't own the named tuple interface. We may need to reconstruct the provider result in this case. It would be nice if we had a way to set the scheme at the provider level.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +                    )
It looks like we did this dance to defer loading the customized builtins until needed and then caching them for future loops. It took a second to realize what was happening so a quick one liner may be helpful.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +                )
How does this surface to the end user? I'm not sure this error is going to be helpful/is potentially breaking if this is triggered before our validation exceptions.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +            raise TypeError("auth_schemes must be a non-empty list.")
Was this still true? I thought Russell had said we should fall back to the service default auth scheme if one isn't provided.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +                # todo: can we handle lists of regions?
Do we have examples where we'd receive a list of regions from the provider? That seems wrong to me. Either we have a single region we're signing for, or a globalized endpoint that usually signs with `aws-global` or `*`. I'm not aware of anything that would support multiple signatures in the same request.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +                from botocore.crt.auth import CRT_AUTH_TYPE_MAPS
Have we tested this out? I'm almost certain this is going to fail because it's importing the CRT at the top of the auth module. If `HAS_CRT` is `False`, we've already shown the required import will fail.

We may need to do something a bit more involved. My immediate thought is something like defining a static list of `CRT_SUPPORTED_AUTH_TYPES` which we validate against here. Then having a test that asserts all keys in `CRT_AUTH_TYPE_MAPS` are in `CRT_SUPPORTED_AUTH_TYPES` to avoid drift over time.

Then this becomes something like:

```python
fixable_with_crt = any([
    scheme['name] for scheme in auth_schemes
    if scheme in CRT_SUPPORTED_AUTH_TYPES
])

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +            ):
This is kind of scary. This effectively makes a backwards compatibility requirement on all error messages from e20. I don't know if I have a better solution, but string matching will likely bite us in the long run. If we do add this, we need some mechanism that's validating the errors from these models never change.

Anything that makes these conditionals no longer match would need to fire in the release pipeline and prevent the change from going out.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/regions.py
> +            ):
Are we trying to avoid other casing variants being captured here, or could we do something like:
```suggestion
            if msg.lower().startswith('invalid arn:'):
```

Also this seems like a potential issue with the error messages themselves? They should be consistent with `ARN` not `Arn`.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
> +        self._cache = cache or {}
Why are we removing the endpoint_bridge here? I think that's going to be considered breaking. Anything that's passing in just the endpoint_bridge and client will now be sending endpoint_bridge->client and client->cache.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
>              return
This seems subtly different. How did we establish confidence that the previous context check directly coorelates with `.s3-accesspoint` in the URL?

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
> +            .get('redirected')
Same note here, the existence of `s3_redirected` implied a redirect previously. With the new check, do we have confidence behavior remains the same?

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
> +        ep_info = self._client._endpoint_resolver_v2.construct_endpoint(
```suggestion
        ep_info = ep_resolver.construct_endpoint(
```

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
> +        return _get_new_endpoint(old_url, new_endpoint, False)
This is also completely changing the way this method works. We may need to do some checks on usage before making a change like this. Otherwise, we should make a new wrapper.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
> +    def redirect_from_cache(self, builtins, operation_name, params, **kwargs):
Same note here, I've got a strong hunch this is going to blow up all of aiobotocore. We may need to work out an alternative way to add this functionality or use keyword args to avoid breaking the signatures.

2022-09-23 17:29 UTC, nateprewitt commented on botocore/utils.py
> -class S3ArnParamHandler:
I don't know if we can wholesale remove these. Was there a reason beyond cleanup? For now we may just need to add a note that the classes are no longer in use and remain for backwards compatibility.

2022-09-23 17:42 UTC, jonemo commented on botocore/regions.py
> +                # todo: can we handle lists of regions?
The spec is:

> The set of signing regions to use for this endpoint. Currently, this will always be ["*"], however this should not be relied upon.

2022-09-23 17:44 UTC, jonemo commented on botocore/regions.py
> +            raise TypeError("auth_schemes must be a non-empty list.")
Correct. This function is for all the logic that applies if `authSchemes` is set. If it's not set, this function never gets called. This `if` covers situations where `authSchemes` is set to a value that doesn't meet spec (and that should be caught during ruleset validation, but added a validation here too just to be defensive).

2022-09-23 17:51 UTC, jonemo commented on botocore/regions.py
> +                    )
Two notes on this:

1. There is a note about the why and what of this a few lines up where `customized_builtins` is defined. 
2. I've already been questioning my decision to execute this lazily. Inside of this function the `before-endpoint-resolution.*` event gets triggered. As a result, this even will be triggered for some operations but not all. This works great for my current use case for the event which is to modify builtin values. But in other situations it's probably better to consistently fire this event for every operation. Thoughts?

2022-09-23 17:53 UTC, jonemo commented on botocore/handlers.py
> +                pass
Good point, David has something similar at the top of the `aws_parse_arn` standard library function. And, as chance would have it, I just added this to the `ArnParser` class yesterday:

```python
    @staticmethod
    def is_arn(value):
        if ':' not in value:
            return False
        arn_parser = ArnParser()
        try:
            arn_parser.parse_arn(value)
            return True
        except InvalidArnException:
            return False
```

I'll go ahead and merge what `aws_parse_arn` does and mine.

2022-09-23 18:10 UTC, nateprewitt commented on botocore/regions.py
> +                    )
1. 🤦‍♂️ I'd read that as a more general "the following logic" comment than specifically being about customized builtins.
2. If there isn't a significant performance hit, shortening it to just this may be simpler:
```python
        customized_builtins = self._get_customized_builtins(operation_name, call_args)
        for param_name, param_def in self._param_definitions.items():
            param_val = self._resolve_param_from_context(
                param_name=param_name,
                op_name=operation_name,
                call_args=call_args,
            )
```

2022-09-23 18:21 UTC, jonemo commented on botocore/utils.py
> -class S3ArnParamHandler:
The deletinos of `S3ArnParamHandler`, `S3EndpointSetter`, and `S3ControlEnpointsetter` are on separate commits so that they can be dropped before merge. I am deleting them on this branch so that I can be certain that they are no longer in use.

2022-09-23 18:26 UTC, jonemo commented on botocore/regions.py
> +            ):
I agree, but I don't see another way and in previous discussions of this nobody else could offer one either. The constraints are:

1. We have tests that assert for the type of exception for specific error cases.
2. We decided that these must not be changed because users may use exception types for control flow.
3. The endpoints rulesets do not know the concept of exception _type_ and only contain information in the message string.

Note that exception messages/text _will_ change and I have deleted assertions against verbiage in some tests.

2022-09-23 18:29 UTC, jonemo commented on botocore/handlers.py
> +                pass
Actually, scratch that. David's code needs validation + parsing in one step. My `is_arn()` is a helper for when only validation is needed but not parsing.

2022-09-23 19:43 UTC, jonemo commented on botocore/args.py
> +                eprv2_region_name = region_name
I wish I knew. The bottom line is that for these two services, the region name gets rewritten during client construction. In some cases multiple times. We have tests that check for these rewrites. Because we need to keep the code where this happens anyway (to continue supporting custom endpoints.json files), I opted for simply using its output instead of attempting to re-implement.

2022-09-23 19:55 UTC, jonemo commented on botocore/handlers.py
>              signature_version = f's3{signature_version}'
My understanding of the different signers was that what botocore calls `s3v4[a]` is the same as the `v4[a]` signer but with double encoding disabled. Prompted by your comment I now learned that there are some additional customizations in the `s3v4[a]` signers.

The s3control endpoint ruleset also uses the `disableDoubleEncoding` property. I am not aware of a different way to disable the double encoding of the URL path, so reverting this change will mean that we ignore this part of the ruleset output.

2022-09-23 19:57 UTC, jonemo commented on botocore/handlers.py
> +def fix_s3_path(model, params, **kwargs):
Yes, the conversation around this was less of a discussion and more of a recounting of constraints. The conclusion was that it will always be the SDK's responsibility to post-process URLs that include bucket names.

2022-09-23 20:02 UTC, jonemo commented on botocore/regions.py
> +            )
Adding this to the provider would be a departure from the (cross-SDK) spec for the provider which does not account for non-secure transport at all. I don't object to doing that, just want to point that out.

Despite its name `_replace` is part of the public and [documented](https://docs.python.org/3/library/collections.html#collections.namedtuple) interface for NamedTuple. From the docs:

> In addition to the methods inherited from tuples, named tuples support three additional methods and two attributes. To prevent conflicts with field names, the method and attribute names start with an underscore.

2022-09-23 20:09 UTC, jonemo commented on botocore/regions.py
> +                )
If the endpoint provider does in fact handle validation for the `required` attribute, then I can remove both this `elif` and the one above. However, I don't see validation for `required` in the endpoint provider.

2022-09-23 21:21 UTC, jonemo commented on botocore/regions.py
> +                from botocore.crt.auth import CRT_AUTH_TYPE_MAPS
You're right, this fails when `awscrt` is not installed. Good catch. I thought I had tested this, but clearly my test setup was lacking.

I will add CRT_SUPPORTED_AUTH_TYPES to `botocore/crt/__init__.py` from where it can be imported without any side effects.

2022-09-28 05:33 UTC, jonemo commented on botocore/utils.py
> +        self._cache = cache or {}
Reverted `endpoint_bridge` back in. Must have gotten lost in the shuffle.

2022-10-07 16:56 UTC, dlm6693 requested changes
Just some high level feedback and code suggestions. Looks pretty good to me overall though.

2022-10-07 16:56 UTC, dlm6693 commented on .pre-commit-config.yaml
> +    tests/functional/endpoint-rules/|\
why do these need to excluded?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/args.py
> +            endpoint_resolver_v2 = None
how about just `endpoint_resolver.py` or `endpoint_resolution.py`?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/client.py
> +            )
do we need to provide `api_version` to this function? Will rule sets be provided for every version or just the latest?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/client.py
> +
This function is absolutely massive. Can we break it up/add some helper functions?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/client.py
> +                    'Endpoing provider returnd list of auth schemes: %s',
nit: Endpoing 😆 and returnd.

Also does it matter if its the other way around or if both of them have auth schemes that don't align?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/endpoint_provider.py
> +                    f"Cannot find value for required parameter {self.name}"
will this error ever be surfaced by a user? if not i think we'd want to stick with using the more generic `EndpointProviderError` or `EndpointResolutionError`

2022-10-07 16:56 UTC, dlm6693 commented on botocore/handlers.py
> +    name and can therefore be addressed before the URL gets assembled.
While reading this context is awesome for understanding the use of this function in this PR, do we really need anything more than the first sentence? I recall getting a lot of feedback to tamp down doc strings.

2022-10-07 16:56 UTC, dlm6693 commented on botocore/handlers.py
> +    `RequiresAccountId` static context parameter in place.
same comment here

2022-10-07 16:56 UTC, dlm6693 commented on botocore/handlers.py
> +    )
i think this can be simplified to
```python
has_ctx_param = any(
    ctx_param.name == 'RequieresAccountId' and ctx_param.value == True 
    for ctx_param in model.static_context_parameters
)

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +        """Invokes the provider with params defined in the services ruleset
nit: service's

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +            )
is there maybe a less manual way to parse this string? Wondering if passing it into `urllib.parse` would be beneficial?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +                return None, {}
I wonder since we do expect some cases to not match if this would be better written as a for loop?
```suggestion
for scheme in auth_schemes:
    if self._does_botocore_authname_match_ruleset_authname(
        self._requested_auth_scheme, scheme['name']
    ):
        name, scheme = self._requested_auth_scheme, scheme
        break

else:
    return None {}

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +                    )
Similar suggestion here
```suggestion
for scheme in auth_schemes:
    if scheme['name'] in AUTH_TYPE_MAPS:
        name, scheme = scheme['name'], scheme
        break
else:
    fixable_with_crt = False
    auth_type_options. = [s['name' for s in auth_schemes]
    if not HAS_CRT:
        fixable_with_crt = any(
            scheme in CRT_SUPPORTED_AUTH_TYPES
            for scheme in auth_type_options
        )

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +                        ' Use pip install botocore[crt] before proceeding.'
Should this be `boto3[crt]` instead?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +                signing_context['region'] = scheme['signingRegionSet'][0]
```suggestion
signing_region = scheme['signingRegionSet'][0]
if len(signing_region) > 0:
    signing_context['region'] = signing_region

2022-10-07 16:56 UTC, dlm6693 commented on botocore/regions.py
> +        * s3-presign-post, sigv4
is all this detail necessary?

2022-10-07 16:56 UTC, dlm6693 commented on botocore/signers.py
> +        )
```suggestion 
signing = context.get('signing', {})
signing_name = signing.get('signing_name', self._signing_name)
region_name =. signing.get('region', self._region_name)

2022-10-07 16:56 UTC, dlm6693 commented on botocore/utils.py
> +        ):
why can't this just be
```python
if '.s3-accesspoint' in previous_request_url:

Is there another case that would contain this substring that we don't want to match?

2022-10-07 21:01 UTC, jonemo commented on .pre-commit-config.yaml
> +    tests/functional/endpoint-rules/|\
Because some of the files lack (or previously lacked, I haven't checked recently) the trailing line break which we have a dedicated check for.

2022-10-07 21:01 UTC, jonemo commented on botocore/client.py
> +            )
We will have a copy of the ruleset in every version folder.

2022-10-07 21:12 UTC, jonemo commented on botocore/handlers.py
> +    name and can therefore be addressed before the URL gets assembled.
I generally agree with your point, but decided to make an exception for this specific case. 

Migrating this "feature" from all the way at the end of the request lifecycle to all the way at the beginning was a much bigger part of the work in this PR than I expected or than what the line count suggests. I am actually about to push a commit that adds _another_ paragraph explaining how this function interacts with the `HmacV1Auth` request signer.

The two reasons I went for lots of detail are:
* I wish there had been more context in the previous version of this. That would have saved me days of debugging and code deep dives.
* If this PR causes problems for any library that imports or patches or otherwise uses internals of botocore, this function has a high likelihood of coming up during debugging. And I think without this context, a natural reaction to reading the code would be: "This can't possibly be right and should be undone!"

2022-10-07 21:17 UTC, jonemo commented on botocore/regions.py
> +                        ' Use pip install botocore[crt] before proceeding.'
The quick answer is: This exception with this exact message already exists in botocore and I only moved it elsewhere.

The longer answer: Good idea because most people who see this exception probably use boto3 and get botocore as a dependency. However, for those people who use botocore directly or as a dependency of something else, it would be wrong to suggest pip-installing boto3[crt] (they don't need boto3). Meanwhile, suggesting to pip install botocore[crt] to someone who uses boto3 is fine.

2022-10-07 21:20 UTC, jonemo commented on botocore/regions.py
> +        * s3-presign-post, sigv4
As a private internal function, this doesn't get direct unit test coverage, otherwise these cases would be listed there. The detailed docstring is my best alternative idea for how to make sure that future code contributors don't inadvertently break one of those cases.

2022-10-07 21:24 UTC, jonemo commented on botocore/utils.py
> +        ):
I wanted to be as specific as possible to avoid any collisions with present or future features. The main cases to think of are that someone could name a bucket `s3-accesspoint-mybucket` and key names.

While writing this answer it actually occurred to me that this looks at the entire URL, so if I name an S3 object key `myobject.s3-accesspoint.txt` it would match. I will fix that by only matching the netloc!

2022-10-17 06:16 UTC, nateprewitt commented on botocore/args.py
>      ):
I'm a little worried about changing the function signature like this. It looks like we're already accounting for endpoints_ruleset_data being `None` below. Can we do the same for partitions and place both of these at the end of the function signature?

```suggestion
        client_config,
        endpoint_bridge,
        auth_token=None,
        endpoints_ruleset_data=None,
        partition_data=None,
    ):
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/args.py
> +            # resolver's output, including final_args, s3_config, ...
```suggestion
            # EndpointRulesetResolver is service-specific. Builtins for
            # EndpointRulesetResolver must not be derived from the legacy endpoint
            # resolver's output, including final_args, s3_config, etc.
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/args.py
> +            client_context = s3_config_raw if service_name_raw == 's3' else {}
Do we have any concerns about case normalization with the raw input? i.e. `s3` v `S3`?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/client.py
> +ENDPOINT_RESOLUTION_V2_SERVICES = ['s3', 's3control']
Can we place these either in utils or the endpoint resolver file? We should avoid hanging these in the client if possible.

2022-10-17 06:16 UTC, nateprewitt commented on botocore/client.py
> +            )
How difficult is it to get `events` onto the list of launch services? Do we have any major test conflicts?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/client.py
> +    # Unused method, kept for potential third party importers
I don't think we need to keep the private methods, there was just concerns about the semi-public classes. Anything with a leading underscore we should be free to mutate as needed.

2022-10-17 06:16 UTC, nateprewitt commented on botocore/client.py
> +                return f's3{suffix}'
For presigned URLs I'd expect MRAP to be using something like `s3v4a-query`. Do you remember what prompted this change?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/client.py
> +                )
This is a case of Black just making a mess. We might be able to amend it with something like:
```suggestion
                auth_info = self._ruleset_resolver.auth_schemes_to_signing_context(
                    auth_schemes
                )
                auth_type, signing_context = auth_info
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/client.py
> -        resolve_checksum_context(request_dict, operation_model, api_params)
Why did we move this into the convert_to_request_dict function?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/crt/__init__.py
> +]
nit; Can we make this a tuple so we're not allocating a mutable list.

2022-10-17 06:16 UTC, nateprewitt commented on botocore/handlers.py
> +    r'[a-zA-Z0-9\-]{1,63}[/:](bucket|accesspoint)[/:][a-zA-Z0-9\-]{1,63}$'
Can you send me a link where this change is coming from? I would not expect us to start allowing bucket arns here.

2022-10-17 06:16 UTC, nateprewitt commented on botocore/handlers.py
> +        return
This is already mounted under s3 for the handler. Was there a reason we added this bailout?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/handlers.py
> +        model.http['authPath'] = f'{req_uri}/' if needs_slash else req_uri
```suggestion
    bucket_path = '/{Bucket}'
    if req_uri.startswith(bucket_path):
        model.http['requestUri'] = req_uri[len(bucket_path):]
        # If the request URI is _only_ a bucket, the auth_path must be
        # terminated with a '/' character to generate a signature that the
        # server will accept.
        needs_slash = req_uri == bucket_path
        model.http['authPath'] = f'{req_uri}/' if needs_slash else req_uri
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/handlers.py
> +    ruleset _and_ the service model place the {AccountId}. prefix the URL.
Not sure if this is what was intended.
```suggestion
    ruleset _and_ the service model place the {AccountId}. prefix in the URL.
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/handlers.py
> +    )
```suggestion
    has_ctx_param = any(
        ctx_param.name == 'RequiresAccountId' and ctx_param.value is True
        for ctx_param in model.static_context_parameters
    )
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/serialize.py
> +        ):
What introduced this case? Is it from a test or something we're not longer receiving?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/signers.py
> +            )
Same layout note here.

2022-10-17 06:16 UTC, nateprewitt commented on botocore/signers.py
> +            ):
```suggestion
            bucket_is_arn = ArnParser.is_arn(params.get('Bucket', ''))
            if 'region' in signing_context and not bucket_is_arn:
```

2022-10-17 06:16 UTC, nateprewitt commented on botocore/signers.py
> +    params = self._emit_api_params(params, operation_model, context)
I'm not sure I understand what's happening here. Why are we emitting the API params at this point?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/signers.py
> +    else:
This block seems very similar to the other presigned else statement in `generate_presigned_url`. Is there anything we share between the two?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/regions.py
> +        actually return an Endpoint object, instead a dict with endpoint info.
This may not be relevant anymore?

2022-10-17 06:16 UTC, nateprewitt commented on botocore/regions.py
> +            if param_val is None and param_def.built_in is not None:
This is more of a note for myself, but we should have stayed consistent and used `param_def.builtin` not `built_in` on the provider. I think we should probably fix that sooner than later.

2022-10-17 06:16 UTC, nateprewitt commented on botocore/regions.py
> +            return 'none', {}
Why was this case `'none'` v `None` elsewhere? I didn't think we allowed a string based option for setting unsigned.

2022-10-19 22:09 UTC, jonemo commented on botocore/args.py
> +        elif client_endpoint_url is not None and not is_s3_accelerate_url(
We could, but it wouldn't help. To shrink this condition, `is_s3_accelerate_url` would have to return `True` for `url=None` which doesn't really make sense.

2022-10-19 22:13 UTC, jonemo commented on botocore/args.py
> +            client_context = s3_config_raw if service_name_raw == 's3' else {}
"raw" here means that it's straight from the service model and not pre-processed by the legacy endpoint resolver or any other upstream logic:

```py
service_name_raw = service_model.endpoint_prefix
```

Therefore, no reason to worry about case normalization.

2022-10-20 00:00 UTC, jonemo commented on botocore/client.py
> +                return f's3{suffix}'
I assume the question is about the change a few lines above and not this specific line?

The short answer: This is no longer needed and I removed it.

This change was needed at the time I wrote it because of the specific ordering of event handlers. Another handler that ran later looked for `v4a` and dealt with it, but didn't look for `s3v4a`. I later changed the order in which the handlers run and therefore this "fix" is no longer necessary.

2022-10-20 00:06 UTC, jonemo commented on botocore/regions.py
> +            return 'none', {}
I got this from [here](https://github.com/boto/botocore/blob/73ce827de52ec52fd2f4e03dc2cdc105627edbfd/botocore/handlers.py#L192-L195).

```python
    # Auth type will be the string value 'none' if the operation should not
    # be signed at all.
    if auth_type == 'none':
        return botocore.UNSIGNED
```

2022-10-20 00:31 UTC, jonemo commented on botocore/client.py
> +                return f's3{suffix}'
Actually, what I wrote above is incorrect. Removing this `if` statement results in the test `functional/test_s3.py::TestAccesspointArn::test_mrap_presigned_url` failing:

```
__________________ TestAccesspointArn.test_mrap_presigned_url __________________

self = <tests.functional.test_s3.TestAccesspointArn testMethod=test_mrap_presigned_url>

    @requires_crt()
    def test_mrap_presigned_url(self):
        mrap_arn = "arn:aws:s3::123456789012:accesspoint:mfzwi23gnjvgw.mrap"
        config = Config(s3={"s3_disable_multiregion_access_points": False})
        expected_url = "mfzwi23gnjvgw.mrap.accesspoint.s3-global.amazonaws.com"
>       self._assert_mrap_presigned_url(
            mrap_arn, "us-west-2", expected_url, config=config
        )

functional/test_s3.py:1128: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
functional/test_s3.py:1186: in _assert_mrap_presigned_url
    self.assertIn("X-Amz-Region-Set=%2A", url_parts.query)
E   AssertionError: 'X-Amz-Region-Set=%2A' not found in 'AWSAccessKeyId=ACCESS_KEY_ID&Signature=2E9ml7RhvJmmjrOrJDYzp7W5TSw%3D&Expires=1666225482'
------------------------------ Captured log call -------------------------------
DEBUG    botocore.hooks:hooks.py:483 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-call.apigateway to before-call.api-gateway
DEBUG    botocore.hooks:hooks.py:483 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
DEBUG    botocore.hooks:hooks.py:483 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
DEBUG    botocore.hooks:hooks.py:483 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
DEBUG    botocore.hooks:hooks.py:483 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
DEBUG    botocore.hooks:hooks.py:483 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
DEBUG    botocore.hooks:hooks.py:483 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
DEBUG    botocore.session:session.py:373 Setting config variable for credentials_file to 'noexist/foo/botocore'
DEBUG    botocore.utils:utils.py:431 IMDS ENDPOINT: http://169.254.169.254/
DEBUG    botocore.credentials:credentials.py:2094 Looking for credentials via: env
INFO     botocore.credentials:credentials.py:1180 Found credentials in environment variables.
DEBUG    botocore.hooks:hooks.py:238 Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f4[562](https://github.com/jonemo/botocore/actions/runs/3285836845/jobs/5413308330#step:5:563)e135e0>
DEBUG    botocore.hooks:hooks.py:238 Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f4[563](https://github.com/jonemo/botocore/actions/runs/3285836845/jobs/5413308330#step:5:564)4ceaf0>
DEBUG    botocore.hooks:hooks.py:238 Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f45634ce8b0>
DEBUG    botocore.endpoint:endpoint.py:408 Setting s3 timeout as (60, 60)
DEBUG    botocore.client:client.py:269 Registering retry handlers for service: s3
DEBUG    botocore.utils:utils.py:1516 Registering S3 region redirector handler
DEBUG    botocore.hooks:hooks.py:238 Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f4562e135e0>
DEBUG    botocore.hooks:hooks.py:238 Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f45634ceaf0>
DEBUG    botocore.hooks:hooks.py:238 Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f45634ce8b0>
DEBUG    botocore.endpoint:endpoint.py:408 Setting s3 timeout as (60, 60)
DEBUG    botocore.client:client.py:269 Registering retry handlers for service: s3
DEBUG    botocore.utils:utils.py:1516 Registering S3 region redirector handler
DEBUG    botocore.hooks:hooks.py:238 Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x7f4562bd90d0>
DEBUG    botocore.hooks:hooks.py:238 Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x7f4562bd9040>
DEBUG    botocore.hooks:hooks.py:238 Event before-parameter-build.s3.GetObject: calling handler <function remove_bucket_from_url_paths_from_model at 0x7f4562bdbe50>
DEBUG    botocore.hooks:hooks.py:238 Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirector2.annotate_request_context of <botocore.utils.S3RegionRedirector2 object at 0x7f45193c4ca0>>
DEBUG    botocore.hooks:hooks.py:238 Event before-parameter-build.s3.GetObject: calling handler <function generate_idempotent_uuid at 0x7f4562e05e50>
DEBUG    botocore.hooks:hooks.py:238 Event before-endpoint-resolution.s3: calling handler <function customize_endpoint_resolver_builtins at 0x7f4562bdc040>
DEBUG    botocore.hooks:hooks.py:238 Event before-endpoint-resolution.s3: calling handler <bound method S3RegionRedirector2.redirect_from_cache of <botocore.utils.S3RegionRedirector2 object at 0x7f45193c4ca0>>
DEBUG    botocore.regions:regions.py:501 Calling endpoint provider with parameters: {'Bucket': 'arn:aws:s3::1234[567](https://github.com/jonemo/botocore/actions/runs/3285836845/jobs/5413308330#step:5:568)89012:accesspoint:mfzwi23gnjvgw.mrap', 'Region': 'us-west-2', 'UseFIPS': False, 'UseDualStack': False, 'ForcePathStyle': False, 'Accelerate': False, 'UseGlobalEndpoint': False, 'DisableMultiRegionAccessPoints': False, 'UseArnRegion': True}
DEBUG    botocore.regions:regions.py:516 Endpoint provider result: https://mfzwi23gnjvgw.mrap.accesspoint.s3-global.amazonaws.com/
DEBUG    botocore.regions:regions.py:654 Selecting from endpoint provider's list of auth schemes: "sigv4a". User selected auth scheme is: "None"
DEBUG    botocore.regions:regions.py:727 Selected auth type "v4a" as "v4a" with signing context params: {'region': '*', 'signing_name': 's3', 'disableDoubleEncoding': True}
DEBUG    botocore.hooks:hooks.py:238 Event choose-signer.s3.GetObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f451b63c7f0>>
DEBUG    botocore.hooks:hooks.py:238 Event before-sign.s3.GetObject: calling handler <function remove_arn_from_signing_path at 0x7f4562bdbf70>
DEBUG    botocore.auth:auth.py:830 Calculating signature using hmacv1 auth.
DEBUG    botocore.auth:auth.py:832 HTTP request method: GET
DEBUG    botocore.auth:auth.py:824 StringToSign:
GET


166[622](https://github.com/jonemo/botocore/actions/runs/3285836845/jobs/5413308330#step:5:623)5482
/obj
```

Didn't catch this locally while researching because I had uninstalled CRT for another deep dive 🤦

2022-10-20 20:58 UTC, jonemo commented on botocore/signers.py
> +    params = self._emit_api_params(params, operation_model, context)
`_emit_api_params` emits two events:

1. `provide-client-params`
2. `before-parameter-build`

Focusing on the latter: `before-parameter-build.s3.*` has many subscribers, including the (new in this PR) `remove_bucket_from_url_paths_from_model` and the (not new in this PR) `validate_bucket_name`. 

`generate_presigned_url` already has the call to `_emit_api_params`. I don't know why this wasn't present in `generate_presigned_post` and why this worked. But together with the other changes in this PR, it is now required for this event to be handled. 

In the context of your other comments about code duplication, I am currently looking whether `_emit_api_params` must be called at this specific line, or whether it can be refactored into a call to `self._convert_to_request_dict`.

2022-10-20 22:45 UTC, jonemo commented on botocore/args.py
> +        if endpoints_ruleset_data is None:
Done in 598f6a5

2022-10-20 22:52 UTC, jonemo commented on botocore/regions.py
> +            )
This could be done with `urllib.parse`, but i don't quite see why. It would only add overhead, both computational and mental for the reader. [urllib doesn't have any special magic for getting the scheme out of a URL, it too just looks for the `:`](https://github.com/python/cpython/blob/49f61068f49747164988ffc5a442d2a63874fc17/Lib/urllib/parse.py#L462-L468).

2022-10-20 22:54 UTC, jonemo commented on botocore/regions.py
> +                # todo: can we handle lists of regions?
I have now removed the `todo` and the code has now slightly change to 

```
        elif 'signingRegionSet' in scheme:
            if len(scheme['signingRegionSet']) > 0:
                signing_context['region'] = scheme['signingRegionSet'][0]
```

But, fundamentally the spec and what we can implement still don't overlap.

2022-10-20 22:59 UTC, jonemo commented on botocore/client.py
> +
The function is indeed massive, and has been before I showed up :) [598f6a5](https://github.com/jonemo/botocore/pull/1/commits/598f6a559ded8c5ee39c520c29c49e88fd096056) refactors this function (and others) to reign in the complexity.

2022-10-20 23:03 UTC, jonemo commented on botocore/client.py
> -        resolve_checksum_context(request_dict, operation_model, api_params)
I moved it back out.

2022-10-21 05:44 UTC, jonemo commented on botocore/utils.py
>              return
We/I didn't establish (enough) confidence and I was actually wrong. I had not accounted for FIPS endpoints and added them shortly after your comment. And today I realized that MRAP accesspoints also look different (`.mrap.accesspoint.`).

1. Switched to doing `ArnParser.is_arn()` on the `Bucket` param (which gets stored in the context for all S3 requests)
2. Added unit test coverage for the MRAP access point case

2022-10-21 05:51 UTC, jonemo commented on botocore/utils.py
> +            .get('redirected')
> do we have confidence behavior remains the same?

Not the same but equivalent. The function previously served by `request_context['s3_redirected']` is now covered by `request_context['s3_redirect']['redirected']`. 

I decided to replace the boolean `s3_redirected` with a dict `s3_redirect` is to make the new `S3RegionRedirector2` self-contained and store all the information it needs in its own namespace within `request_dict`. The previous version relied on information stored in the `request_context` dict by `S3EndpointSetter`.

2022-10-21 05:56 UTC, jonemo commented on botocore/utils.py
> +        return _get_new_endpoint(old_url, new_endpoint, False)
Does your concern still apply now that the old code remains in place (but unused) in `S3RegionRedirector` and the new code is in `S3RegionRedirector2`?

2022-10-21 09:11 UTC, nateprewitt commented on botocore/regions.py
> +            )
Manual url parsing (URL Parsing Confusion) is a pretty big vector for attacks, so _generally_ you want to avoid doing any of it yourself. That said, what we're doing here is very tightly scoped to the scheme and only a single set of prefixing characters.

I think I'm alright with this given there aren't other great options. We'll test new Python versions before they release so if this interface does ever change we should catch it.

2022-10-21 09:11 UTC, nateprewitt commented on botocore/regions.py
> +                # todo: can we handle lists of regions?
I almost want to add an error here. We need a way to know when this happens and make sure we do whatever the expected behavior is before a release happens. Presumably that will come through intake, but I'm not convinced this won't accidentally slip into a release with undefined behavior.

2022-10-21 09:11 UTC, nateprewitt commented on botocore/handlers.py
> +    name and can therefore be addressed before the URL gets assembled.
This is sufficiently nuanced, I think we should keep the level of detail here. There's nowhere else this decision process is documented beyond this code, unlike features that are implemented from a spec.

2022-10-21 09:11 UTC, nateprewitt commented on botocore/handlers.py
> +    `RequiresAccountId` static context parameter in place.
Again, I'd say this is needed. This is somewhat unintuitive behavior and it needs to be clear why we added this.

2022-10-21 09:11 UTC, nateprewitt commented on botocore/regions.py
> +        * s3-presign-post, sigv4
This ones a bit verbose, but I don't think the examples hurt. I'm fine leaving this as is.

2022-10-21 14:27 UTC, jonemo commented on botocore/handlers.py
> +    r'[a-zA-Z0-9\-]{1,63}[/:](bucket|accesspoint)[/:][a-zA-Z0-9\-]{1,63}$'
It looks like I misunderstood the details of S3 on Outpost. But I would also say that there is additionally scope for a small improvement in this:

I assumed that _all_ S3 operations that get a bucket param are validated by [the `validate_bucket_name` function](https://github.com/boto/botocore/blob/7d4a3fc41928155a4a1eac04c02b68af64a3a59d/botocore/handlers.py#L268-L278) where this regex gets used. And according to [the table in this documentation section](https://docs.aws.amazon.com/AmazonS3/latest/userguide/S3OutpostsWorkingBuckets.html#S3OutpostsBucketAPIs, there are operations for S3 on Outpost that require the bucket ARN, not the Accesspoint ARN, as parameter. 

However, all the operations in question are of the kind where the regular S3 operation uses the `s3` client but for S3 on Outpost we use the `s3control` client. `validate_bucket_name()` is only used for the `s3` client. Therefore, the S3 on Outpost bucket ARNs never pass through the bucket name validation.

I will remove this change from the PR. What do you think about a backlog task to expand bucket name validation to `s3control`?

2022-10-21 14:33 UTC, jonemo commented on botocore/regions.py
> +                # todo: can we handle lists of regions?
We do have a new test `tests/function/test_endpoint_rulesets.py:assert_all_signing_region_sets_have_length_one` to make noise if we ever get a list with length >1.

2022-10-21 14:42 UTC, jonemo commented on botocore/regions.py
> +            if param_val is None and param_def.built_in is not None:
Ok, done.

2022-10-21 16:40 UTC, nateprewitt commented on botocore/handlers.py
> +    r'[a-zA-Z0-9\-]{1,63}[/:](bucket|accesspoint)[/:][a-zA-Z0-9\-]{1,63}$'
That would be a change for all SDKs, so we'd need to discuss that at an org level and then with s3 before we schedule anything. Maybe something to bring up for discussion today.

2022-10-24 15:55 UTC, jonemo commented on botocore/client.py
> +            )
Answered indirectly with https://github.com/boto/botocore/pull/2788

2022-10-24 17:19 UTC, jonemo commented on botocore/handlers.py
> +    r'[a-zA-Z0-9\-]{1,63}[/:](bucket|accesspoint)[/:][a-zA-Z0-9\-]{1,63}$'
For posterity: This change has been reverted in the final (non-WIP) version of this PR: https://github.com/boto/botocore/pull/2785

2022-10-24 17:19 UTC, jonemo commented
The non-WIP version of this PR is here: https://github.com/boto/botocore/pull/2785

2022-10-24 17:19 UTC, closed without merging

2022-10-24 17:34 UTC, jonemo commented on botocore/serialize.py
> +        ):
This became necessary as a side effect of the new handler `remove_accid_host_prefix_from_model`. This handler preprocesses the s3control service model to remove the `{AccountId}.` host prefix because the endpoint ruleset provider handles appending this now.

The alternative would have been to more comprehensively modify the service model and also remove the entire `endpoint` field if it is empty. I opted to instead add this check here and make the serializer slightly more defensive against the model inputs it receives.